### ISSUE TITLE
Error starting project in GNURadio

### ISSUE THREAD

**Issue by astrokor** [rigexpert/gr-rigexpert#8]
I see this output in GnuRadio. How can I fix it?
"libgnuradio-RigExpert" links and library are installed in the OS. 

<<< Welcome to GNU Radio Companion 3.10.1.1 >>>

Block paths:
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/rusik/Projects/GNU Radio/test_fobos.grc"
>>> Done

Generating: '/home/rusik/Projects/GNU Radio/test_fobos.py'

Executing: /usr/bin/python3 -u /home/rusik/Projects/GNU Radio/test_fobos.py

Traceback (most recent call last):
  File "/home/rusik/Projects/GNU Radio/test_fobos.py", line 27, in <module>
    from gnuradio import RigExpert
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/RigExpert/__init__.py", line 18, in <module>
    from .RigExpert_python import *
ImportError: libgnuradio-RigExpert.so.1.0.0: cannot open shared object file: No such file or directory

>>> Done (return code 1)

**Comment by astrokor** [comment]
I couldn't fix it.
But when I updated the packages in my OS, the project built and started.
